config/routes.rb
Rails.application.routes.draw do
  mount NdrError::Engine => '/fingerprinting'
  mount NdrAuthenticate::Engine, at: '/auth' if Rails.configuration.x.use_ndr_authenticate

  get '/users/sign_in', to: redirect('/auth/sign_in') if Rails.configuration.x.use_ndr_authenticate

  # NOTE: NdrAuth cannot at present pick up a custom `after_sign_in_path_for` defined by the
  # host app. Since it will always redirect to `main_app.root_path` we can instead change what
  # controller/action the host app understands '/' to be for different contexts and achieve a
  # similar result.
  authenticated :user, ->(user) { !user.standard? } do
    root 'projects#dashboard', as: :non_standard_authenticated_root
  end

  authenticated :user, ->(user) { user.cas_role? } do
    root 'projects#index', as: :cas_role_authenticated_root
  end

  authenticated :user, ->(user) { user.standard? && !user.cas_role? } do
    root 'home#index', as: :applicant_authenticated_root
  end

  root 'home#index'

  concern :downloadable do
    get :download, on: :member
  end

  concern :commentable do |options|
    defaults = {
      shallow: true,
      only:    %i[index create destroy]
    }

    resources :comments, defaults.merge(options)
  end

  concern :approvable do |options|
    default_options = {
      only: %i[new create destroy]
    }

    resource :approval,  default_options.merge(options)
    resource :rejection, default_options.merge(options)
  end

  get 'notifications/index'
  get '/reports/report1', to: 'reports#report1', as: 'report1'
  get '/reports/report2', to: 'reports#report2', as: 'report2'

  resources :reports, only: %i[show]

  get '/downloads/data_access_agreement', to: 'downloads#data_access_agreement',
                                          as: 'data_access_agreement'
  get '/downloads/ons_declaration_of_use', to: 'downloads#ons_declaration_of_use',
                                           as: 'ons_declaration_of_use'
  get '/downloads/ons_short_declaration_list', to: 'downloads#ons_short_declaration_list',
                                               as: 'ons_short_declaration_list'
  get '/downloads/terms_and_conditions_doc', to: 'downloads#terms_and_conditions_doc',
                                         as: 'terms_and_conditions_doc'
  get '/downloads/project_end_users_template_csv', to: 'downloads#project_end_users_template_csv',
      as: 'project_end_users_template_csv'

  # for dynamic select boxes in team and user
  get 'filter_delegates_by_division', to: 'users#filter_delegates_by_division',
                                      as: 'filter_delegates_by_division'

  get 'ons_template', to: 'projects#ons_template'

  # TODO: Remove once NdrAuthenticate is ready for the prime time.
  unless Rails.configuration.x.use_ndr_authenticate
    devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' },
                       skip: :saml_authenticatable
  end

  resources :notifications, :directorates, :divisions

  resources :users do
    resources :grants, only: [:index] do
      collection do
        get :edit_team
        get :edit_system
        get :edit_project
        get :edit_dataset
        patch :update
      end
    end
    get :teams
    get :projects
  end

  resources :projects do
    get :dashboard, on: :collection
    get :cas_approvals, on: :collection
    patch :project_dataset_levels_bulk_approvals, on: :member
    put :project_dataset_levels_bulk_approvals, on: :member
    patch :project_dataset_levels_bulk_renewal_requests, on: :member
    put :project_dataset_levels_bulk_renewal_requests, on: :member
  end

  resources :projects, shallow: true do
    resources :project_datasets, shallow: true do
      resources :project_dataset_levels do
        member do
          patch :approve
          put :approve
          patch :reject
          put :reject
          patch :reapply
          put :reapply
          patch :renew
          get :renew
        end
      end
    end
  end

  get :servicestatus, to: 'home#servicestatus'
  resources :home, only: [:index]

  resources :terms_and_conditions, only: [:index, :create]

  resources :active_team, only: [:index, :update]

  resources :data_sources, shallow: true do
    resources :data_source_items
  end

  resources :table_specifications, only: [:index]
  resources :data_assets, only: [:index]
  resources :datasets, shallow: true do
    resources :dataset_versions, shallow: true do
      resources :categories
      resources :nodes do
        collection do
          patch :sort
        end
        resources :node_categories do
          collection do
            patch :update
          end
        end
      end
      resources :data_items do
        member do
          get :edit_error, to: 'data_items#edit_error', as: :edit_error
          patch :edit_error, to: 'data_items#update_error', as: :update_error
        end
      end
      resources :entities do
        member do
          get :edit_error, to: 'entities#edit_error', as: :edit_error
          patch :edit_error, to: 'entities#update_error', as: :update_error
        end
      end
      resources :choices do
        member do
          get :edit_error, to: 'choices#edit_error', as: :edit_error
          patch :edit_error, to: 'choices#update_error', as: :update_error
        end
      end
      resources :groups do
        member do
          get :edit_error, to: 'groups#edit_error', as: :edit_error
          patch :edit_error, to: 'groups#update_error', as: :update_error
        end
      end
      resources :category_choices, :node_errors
      patch :publish, on: :member
      get "download/:id" => "dataset_versions#download", as: :download
    end
  end

  resources :user_notifications
  patch :mark_notification_as_read, to: 'user_notifications#mark_as_read'

  resources :organisations, shallow: true do
    resources :teams
  end

  patch :default_address, to: 'addresses#default_address'

  resources :teams, shallow: true, except: %i[new create] do
    resources :datasets
    resources :memberships
    resources :grants, controller: :team_grants do
      collection do
        get :edit
        patch :update
      end
    end
    resources :team_datasets, only: [:index, :new, :create, :destroy]
    resources :projects, shallow: true, concerns: %i[commentable] do
      resources :grants, controller: :project_grants do
        collection do
          get :edit
          patch :update
        end
      end
      resources :project_memberships, only: [:index, :new, :create, :destroy]
      resources :project_data_end_users
      resources :project_attachments

      resources :project_nodes, except: %i[edit update], concerns: %i[commentable] do
        concerns :approvable, module: 'project_nodes'

        collection do
          scope :bulk, module: :project_nodes, only: %i[new create destroy] do
            resource :approvals,  controller: :bulk_approvals,  as: :project_nodes_bulk_approval
            resource :rejections, controller: :bulk_rejections, as: :project_nodes_bulk_rejection
          end
        end
      end

      resources :amendments, controller: :project_amendments, as: :project_amendments
      resources :data_privacy_impact_assessments, concerns: %i[downloadable]
      resources :contracts, concerns: %i[downloadable]
      resources :releases
      resources :communications, except: %i[show edit update], concerns: %i[commentable]

      namespace :workflow do
        resources :project_states, only: [] do
          concerns :commentable, controller: '/comments'
          resources :assignments, only: %i[create]
        end
      end

      collection do
        post :import, controller: 'projects/imports', action: :create
      end

      resources :imports, only: :create, controller: 'projects/imports'

      resource :details, only: [], concerns: %i[approvable], module: 'projects/details'
      resource :legal,   only: [], concerns: %i[approvable], module: 'projects/legal'
      resource :members, only: [], concerns: %i[approvable], module: 'projects/members'

      member do
        # FIXME: This should be PATCH
        get :reset_project_approvals
        get :edit_data_source_items
        get :edit_ons_data_access
        get :edit_ons_declaration
        get :show_ons_access_agreement
        get :show_ons_declaration_use
        get :show_ons_declaration_list
        get :duplicate
        patch :assign
        patch :transition
      end
    end
  end

  resources :jobs, only: %i[index show destroy]

  get '/terms_rejected', to: 'terms_and_conditions#terms_rejected', as: 'terms_rejected'

  get ':resource_type/:resource_id/versions',     to: 'versions#index', as: :papertrail_versions
  get ':resource_type/:resource_id/versions/:id', to: 'versions#show',  as: :papertrail_version

  # Allowing logged-in user to change their password:
  get  'change_password', to: 'users/password_changes#new'
  post 'change_password', to: 'users/password_changes#create'
end

app/models/notification.rb
# Logic assigning Notifcations to Users
# based on User permissions/roles
# The Notifciation table is the master 'notification' - there is then a UserNotifications table for specific users
# The Notification table flags the 'type' of user the message should go to eg admin, project member, odr.
# The UserNotifciations are generated based on these flags of type of user
class Notification < ActiveRecord::Base
  scope :admin_users, -> { where admin_users: true }
  scope :odr_users, -> { where odr_users: true }
  scope :senior_users, -> { where senior_users: true }
  scope :by_title, ->(title) { where title: title }
  # scope :active, -> { where.not(status: 'deleted') }
  # scope :deleted, -> { where(status: 'deleted') }

  has_many :user_notifications, dependent: :destroy
  has_many :users, through: :user_notifications
  belongs_to :team, optional: true
  belongs_to :project, optional: true
  after_create :create_user_notifications
  after_create :send_admin_email

  # FIXME: Decouple presentation layer from persistence layer
  attribute :generate_mail, :boolean, default: true

  def users_not_to_notify
    @users_not_to_notify ||= Set.new
  end

  # all of the notifications will be sent to relevant users
  def users_to_notify
    Set.new.tap do |set|
      set.merge(User.in_use.ids) if all_users
      set.merge(User.administrators.ids) if admin_users
      set.merge(User.odr_users.ids) if odr_users
      set.merge(project_user_ids) if project
      set.merge(team.users.ids) if team
      set.add(user_id) if user_id

      set.subtract(users_not_to_notify)
    end
  end

  private

  def create_user_notifications
    users_to_notify.each do |user_id|
      user_notifications.create(user_id: user_id, generate_mail: generate_mail)
    end
  end

  def send_admin_email
    return unless generate_mail
    return unless admin_users
    NotificationMailer.send_admin_messages(self).deliver_later
  end

  # attempt to not tread on MBIS application behaviour for now until
  # notifications ana mail is fully decoupled
  def project_user_ids
    return [] if project_id.nil?

    project.users.internal.pluck(:id)
  end
end

app/controllers/notifications_controller.rb
# This controller restfully manages MBIS notifications
class NotificationsController < ApplicationController
  # load_and_authorize_resource
  respond_to :js, :html

  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)
    if @notification.save
      flash[:notice] = 'All users sucessfully messaged'
      flash.keep(:notice)
      render js: "window.location = '/'"
    else
      render :new
    end
  end

  def index
    if !params[:deleted].nil? && params[:deleted] == '1'
      @notifications = current_user.user_notifications.deleted.order('created_at desc')
    else
      @notifications = current_user.user_notifications.inbox.order('created_at desc')
    end
    # these are for search boxes
    @teams = [['All', 'All']]
    if current_user.administrator? || current_user.odr?
      @teams.concat Team.active.order('name').collect { |a| [a.name, a.id] }
    else
      @teams.concat current_user.teams.active.order('name').collect { |a| [a.name, a.id] }
    end

    if !params[:team].nil? && params[:team] != 'All'
      @notifications = @notifications.team(params[:team])
      # projects = Team.find(params[:team]).projects.collect(&:id)
    end
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def notification_params
    params.require(:notification).permit(:title, :body, :created_by, :all_users)
  end
end

app/views/notifications/_detail.html.erb
<td colspan="12" style="padding:0">
  <div id="<%= dom_id(notification) %>_details" class="collapse" style="padding: 0 0em">
    <div style="padding-left: 40px">
      <div class="arrow-up"></div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            <div class="pull-left" style="font-size:1em">
              <%= notification.title%> <%= timeago_tag(notification.created_at) %>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-body" style="padding-top:8px;padding-bottom:30px">
        <%= simple_format(notification.body) %>
      </div>
    </div>
  </div>
</td>

app/views/notifications/_form.html.erb
<%= bootstrap_form_for @notification, horizontal: 2 do |form| %>
  <div class="row">
    <div class=" col-md-12">
        <div class="panel-footer">
          <%= bootstrap_form_for @notification, horizontal: 2 do |form| %>
            <%= form.hidden_field :created_by, value: current_user.id %>
            <%= form.hidden_field :all_users, value: true %>
            <%= form.control_group :title, 'Title' do %>
              <%= form.text_field :title %>
            <% end %>

            <%= form.control_group :body, 'Message' do %>
              <%= form.text_area :body, rows: 15 %>
            <% end %>
            <%= form.control_group nil do %>
              <div class='pull-right'>
                <%= cancel_submit @notification %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/notifications/_notifications.html.erb
<table class="table table-hover" id="notifications_table">
  <thead>
    <th>Subject</th>
    <th>Details</th>
    <th>Team</th>
    <th>Created</th>
  </thead>
  <tbody>
    <% notifications.each do |n|
      notification = n.notification %>
      <tr id="<%= dom_id(notification) %>" class="<%= 'unread_notification' if n.status == 'new' %>">
        <td width="15%">
          <%= notification.title %>
        </td>
        <td width="40%">
          <%= truncate(notification.body, length: 80, separator: ' ') %>
          <span data-toggle="collapse" data-target="#<%= dom_id(notification) %>_details">
            <% if n.status == 'new' %>
              <%= link_to 'more', mark_notification_as_read_path(:id => n.id, "user_notification[status]" => 'read'), :method => :patch,
                   remote: true, class: 'more_or_less',
                   id: "notification_#{n.id.to_s}_link" %>
            <% else %>
              <a href="#" class="more_or_less" data-turbolinks="false">more</a>
            <% end %>
          </span>
        </td>
        <td width="20%"><%= notification.team.name if !notification.team.nil?%></td>
        <td width="15%">
          <%= notification.created_at.strftime('%d-%b-%y %H:%M') %>
          <div class="pull-right">
            <%= button_group do %>
              <%# if can?(:destroy, n) && n.status != 'deleted'%>
                <%= delete_link(n, method: :delete, data: { confirm: 'Are you sure you want to delete this notification' }, id: 'delete_notification' )%>
              <%# end %>
            <% end %>
          </div>
        </td>
      </tr>
      <tr class="comments">
        <%= render 'detail', notification: notification %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notifications/index.html.erb
<%= bootstrap_panel_tag(capture { %>
  <div class='row'>

  	<div class='col-md-9'>

        <%= form_tag notifications_path, method: :get, class: "form-inline"  do %>
        <h4>Notifications -
        <small>Filter by Team
          <%= select_tag :team, options_for_select(@teams, params[:team]), class: 'form-control', selected: params[:team] %></small>
        <small>Deleted <%= check_box_tag :deleted, 1, params[:deleted], class: 'form-control' %></small>
        <%= submit_tag "Search", class: "btn btn-default btn-sm" %>
        </h4>
      <%end %>



    </div>


   <% if current_user.administrator? %>
     <div class='col-md-3 text-right'>
  	   <%= link_to 'Message all users', new_notification_path(Notification.new), remote: true, class: 'btn btn-default' %>
     </div>
   <% end %>
  </div>
  <% if current_user.standard? && current_user.teams.active.count.zero? %>
    <h4>
      <strong>You are not currently a member of any teams. Please contact
      an Administrator or an Application Manager to be added to a Team</strong>
    </h4>
  <% end %>
<% }) do %>
<% end %>
<div id='notifications_div'>
<%= render 'notifications', notifications: @notifications unless @notifications.nil? %>
</div>

app/views/notifications/new.html.erb
<%= bootstrap_form_for @notification, horizontal: 2 do |form| %>
  <div class="row">
    <div class=" col-md-12">
        <div class="panel-footer">
          <%= bootstrap_form_for @notification, horizontal: 2 do |form| %>
            <%= form.control_group :body, 'Message' do %>
              <%= form.text_area :body %>
            <% end %>
            <%= form.control_group nil do %>
              <div class='pull-right'>
                <%= cancel_submit @notification %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/notifications/new.js.erb
<%
  html_content = escape_javascript bootstrap_form_for([@notification], remote: true, horizontal: 2) { |form| render('form', form: form) }
%>

jQuery('#modal_title').html('Create broadcast notification for all users');
jQuery('#modal_body').html('<%= html_content %>').parents('.modal').modal('show');