config/routes.rb
Rails.application.routes.draw do
  mount NdrError::Engine => '/fingerprinting'
  mount NdrAuthenticate::Engine, at: '/auth' if Rails.configuration.x.use_ndr_authenticate

  get '/users/sign_in', to: redirect('/auth/sign_in') if Rails.configuration.x.use_ndr_authenticate

  # NOTE: NdrAuth cannot at present pick up a custom `after_sign_in_path_for` defined by the
  # host app. Since it will always redirect to `main_app.root_path` we can instead change what
  # controller/action the host app understands '/' to be for different contexts and achieve a
  # similar result.
  authenticated :user, ->(user) { !user.standard? } do
    root 'projects#dashboard', as: :non_standard_authenticated_root
  end

  authenticated :user, ->(user) { user.cas_role? } do
    root 'projects#index', as: :cas_role_authenticated_root
  end

  authenticated :user, ->(user) { user.standard? && !user.cas_role? } do
    root 'home#index', as: :applicant_authenticated_root
  end

  root 'home#index'

  concern :downloadable do
    get :download, on: :member
  end

  concern :commentable do |options|
    defaults = {
      shallow: true,
      only:    %i[index create destroy]
    }

    resources :comments, defaults.merge(options)
  end

  concern :approvable do |options|
    default_options = {
      only: %i[new create destroy]
    }

    resource :approval,  default_options.merge(options)
    resource :rejection, default_options.merge(options)
  end

  get 'notifications/index'
  get '/reports/report1', to: 'reports#report1', as: 'report1'
  get '/reports/report2', to: 'reports#report2', as: 'report2'

  resources :reports, only: %i[show]

  get '/downloads/data_access_agreement', to: 'downloads#data_access_agreement',
                                          as: 'data_access_agreement'
  get '/downloads/ons_declaration_of_use', to: 'downloads#ons_declaration_of_use',
                                           as: 'ons_declaration_of_use'
  get '/downloads/ons_short_declaration_list', to: 'downloads#ons_short_declaration_list',
                                               as: 'ons_short_declaration_list'
  get '/downloads/terms_and_conditions_doc', to: 'downloads#terms_and_conditions_doc',
                                         as: 'terms_and_conditions_doc'
  get '/downloads/project_end_users_template_csv', to: 'downloads#project_end_users_template_csv',
      as: 'project_end_users_template_csv'

  # for dynamic select boxes in team and user
  get 'filter_delegates_by_division', to: 'users#filter_delegates_by_division',
                                      as: 'filter_delegates_by_division'

  get 'ons_template', to: 'projects#ons_template'

  # TODO: Remove once NdrAuthenticate is ready for the prime time.
  unless Rails.configuration.x.use_ndr_authenticate
    devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' },
                       skip: :saml_authenticatable
  end

  resources :notifications, :directorates, :divisions

  resources :users do
    resources :grants, only: [:index] do
      collection do
        get :edit_team
        get :edit_system
        get :edit_project
        get :edit_dataset
        patch :update
      end
    end
    get :teams
    get :projects
  end

  resources :projects do
    get :dashboard, on: :collection
    get :cas_approvals, on: :collection
    patch :project_dataset_levels_bulk_approvals, on: :member
    put :project_dataset_levels_bulk_approvals, on: :member
    patch :project_dataset_levels_bulk_renewal_requests, on: :member
    put :project_dataset_levels_bulk_renewal_requests, on: :member
  end

  resources :projects, shallow: true do
    resources :project_datasets, shallow: true do
      resources :project_dataset_levels do
        member do
          patch :approve
          put :approve
          patch :reject
          put :reject
          patch :reapply
          put :reapply
          patch :renew
          get :renew
        end
      end
    end
  end

  get :servicestatus, to: 'home#servicestatus'
  resources :home, only: [:index]

  resources :terms_and_conditions, only: [:index, :create]

  resources :active_team, only: [:index, :update]

  resources :data_sources, shallow: true do
    resources :data_source_items
  end

  resources :table_specifications, only: [:index]
  resources :data_assets, only: [:index]
  resources :datasets, shallow: true do
    resources :dataset_versions, shallow: true do
      resources :categories
      resources :nodes do
        collection do
          patch :sort
        end
        resources :node_categories do
          collection do
            patch :update
          end
        end
      end
      resources :data_items do
        member do
          get :edit_error, to: 'data_items#edit_error', as: :edit_error
          patch :edit_error, to: 'data_items#update_error', as: :update_error
        end
      end
      resources :entities do
        member do
          get :edit_error, to: 'entities#edit_error', as: :edit_error
          patch :edit_error, to: 'entities#update_error', as: :update_error
        end
      end
      resources :choices do
        member do
          get :edit_error, to: 'choices#edit_error', as: :edit_error
          patch :edit_error, to: 'choices#update_error', as: :update_error
        end
      end
      resources :groups do
        member do
          get :edit_error, to: 'groups#edit_error', as: :edit_error
          patch :edit_error, to: 'groups#update_error', as: :update_error
        end
      end
      resources :category_choices, :node_errors
      patch :publish, on: :member
      get "download/:id" => "dataset_versions#download", as: :download
    end
  end

  resources :user_notifications
  patch :mark_notification_as_read, to: 'user_notifications#mark_as_read'

  resources :organisations, shallow: true do
    resources :teams
  end

  patch :default_address, to: 'addresses#default_address'

  resources :teams, shallow: true, except: %i[new create] do
    resources :datasets
    resources :memberships
    resources :grants, controller: :team_grants do
      collection do
        get :edit
        patch :update
      end
    end
    resources :team_datasets, only: [:index, :new, :create, :destroy]
    resources :projects, shallow: true, concerns: %i[commentable] do
      resources :grants, controller: :project_grants do
        collection do
          get :edit
          patch :update
        end
      end
      resources :project_memberships, only: [:index, :new, :create, :destroy]
      resources :project_data_end_users
      resources :project_attachments

      resources :project_nodes, except: %i[edit update], concerns: %i[commentable] do
        concerns :approvable, module: 'project_nodes'

        collection do
          scope :bulk, module: :project_nodes, only: %i[new create destroy] do
            resource :approvals,  controller: :bulk_approvals,  as: :project_nodes_bulk_approval
            resource :rejections, controller: :bulk_rejections, as: :project_nodes_bulk_rejection
          end
        end
      end

      resources :amendments, controller: :project_amendments, as: :project_amendments
      resources :data_privacy_impact_assessments, concerns: %i[downloadable]
      resources :contracts, concerns: %i[downloadable]
      resources :releases
      resources :communications, except: %i[show edit update], concerns: %i[commentable]

      namespace :workflow do
        resources :project_states, only: [] do
          concerns :commentable, controller: '/comments'
          resources :assignments, only: %i[create]
        end
      end

      collection do
        post :import, controller: 'projects/imports', action: :create
      end

      resources :imports, only: :create, controller: 'projects/imports'

      resource :details, only: [], concerns: %i[approvable], module: 'projects/details'
      resource :legal,   only: [], concerns: %i[approvable], module: 'projects/legal'
      resource :members, only: [], concerns: %i[approvable], module: 'projects/members'

      member do
        # FIXME: This should be PATCH
        get :reset_project_approvals
        get :edit_data_source_items
        get :edit_ons_data_access
        get :edit_ons_declaration
        get :show_ons_access_agreement
        get :show_ons_declaration_use
        get :show_ons_declaration_list
        get :duplicate
        patch :assign
        patch :transition
      end
    end
  end

  resources :jobs, only: %i[index show destroy]

  get '/terms_rejected', to: 'terms_and_conditions#terms_rejected', as: 'terms_rejected'

  get ':resource_type/:resource_id/versions',     to: 'versions#index', as: :papertrail_versions
  get ':resource_type/:resource_id/versions/:id', to: 'versions#show',  as: :papertrail_version

  # Allowing logged-in user to change their password:
  get  'change_password', to: 'users/password_changes#new'
  post 'change_password', to: 'users/password_changes#create'
end

app/controllers/dataset_versions_controller.rb
# This controller RESTfully manages Dataset Versions
class DatasetVersionsController < ApplicationController
  load_and_authorize_resource :dataset
  load_and_authorize_resource :dataset_version, through: :dataset, shallow: true

  respond_to :js, :html

  def new; end

  def show
    @readonly = true
    @fluid_layout = true
  end

  def create
    @dataset_version.send(:create_version_entity)
    if @dataset_version.save
      respond_to do |format|
        format.html { redirect_to datasets_path, notice: 'Version was successfully created.' }
        format.js
      end
    else
      render :new
    end
  end

  def update
    if @dataset_version.update(dataset_version_params)
      respond_to do |format|
        message = 'Dataset Version was successfully updated.'
        format.html { redirect_to datasets_path, notice: message }
        format.js { render :index }
      end
    else
      render :edit
    end
  end

  def download
    if @dataset_version.send(:nodes_valid_for_schema_build?)
      # TODO: publish should save the new version number and finalise version
      filename = @dataset_version.send(:zip_filename)
      temp_file = Tempfile.new(filename)

      begin
        SchemaPack.new(@dataset_version, nil, temp_file)
        zip_data = File.read(temp_file.path)
        send_data(zip_data, type: 'application/zip', disposition: 'attachment', filename: filename)
      ensure
        temp_file.close
        temp_file.unlink
      end
    else
      @dataset_version_invalid_nodes = @dataset_version.send(:invalid_nodes_for_schema_build)
      render :errors
    end
  end

  def publish
    if @dataset_version.send(:nodes_valid_for_schema_build?)
      @dataset_version.update_attribute(:published, true)
      redirect_to @dataset_version
    else
      @dataset_version_invalid_nodes = @dataset_version.send(:invalid_nodes_for_schema_build)
      render :errors
    end
  end

  def destroy
    @datasets = Dataset.all
    if @dataset_version.destroy
      respond_to do |format|
        msg = 'DatasetVersion was successfully destroyed.'
        format.html { redirect_to "/teams/#{@dataset_version.dataset.team.id}#!datasets",
                      notice: msg }
        format.js
      end
    else
      respond_to do |format|
        msg = 'Could not destroy version!'
        format.html { redirect_to "/teams/#{@dataset_version.dataset.team.id}#!datasets",
                      notice: msg }
        format.js { render js: "alert('#{msg}')" }
      end
    end
  end
  
  private

  # Only allow a trusted parameter "white list" through.
  def dataset_version_params
    params.require(:dataset_version).permit(:id, :semver_version, :dataset_id, :published)
  end
end

app/helpers/dataset_version_helper.rb
module DatasetVersionHelper
  def ancestors(parent)
    ancestor_array = []

    while parent = parent.parent_node
      ancestor_array << parent
    end

    ancestor_array
  end

  def render_tree(root, selected_node = nil, ancestors = [], depth = 0)
    # return unless ancestors.include?(root) || root == selected_node || root.parent_node == selected_node

    html = render('nodes/tree_details',
                  node: root, depth: depth, ancestor: ancestors.include?(root),
                  selected_node: selected_node)
    root.child_nodes.sorted.each do |node|
      next if node.data_item?

      html += render_tree(node, selected_node, ancestors, depth + 1)
    end
    html
  end

  def dataset_download_link(from_tree = true)
    return unless @dataset_version.dataset.dataset_type.name == 'xml'
    return unless can?(:download, DatasetVersion)

    link_class = action_link_class(from_tree)

    link_to('Download', dataset_version_download_path(@dataset_version, @dataset_version),
            class: link_class, 'data-turbolinks' => false, id: 'publish')
  end

  def publish_tr_class(v)
    return 'danger' unless v.published
  end

  def publish_link(from_tree = true)
    return published_state_button if @dataset_version.published
    return unless can?(:publish, DatasetVersion)

    link_class = action_link_class(from_tree)

    link_to('Publish', publish_dataset_version_path(@dataset_version), method: :patch,
            class: link_class, 'data-turbolinks' => false, id: 'publish')
  end

  def published_state_button
    button_tag('Published', class: 'btn btn-sm btn-info')
  end

  def action_link_class(from_tree = true)
    if from_tree
      'btn btn-sm btn-success'
    elsif @dataset_version.send(:invalid_nodes_for_schema_build).present?
      'btn btn-sm btn-danger'
    else
      'btn btn-sm btn-success'
    end
  end

  def dataset_versions_for_user(dataset)
    dataset.dataset_versions.order('semver_version').reverse.each_with_object([]) do |dv, list|
      list << dv if can?(:read, dv)
    end
  end

  def dataset_type_label(dataset)
    content_tag(:span, dataset.dataset_type_name, class: 'label label-primary')
  end

  def child_node_table_id(dataset_version)
    return unless can?(:update, dataset_version)
    return if dataset_version.published

    'table-child-nodes-sortable'
  end
end

app/views/dataset_versions/_child_nodes_table.html.erb
<%
# set default local variable(s)
divider = nil if local_assigns[:divider].nil?
%>
<table class="table <%=child_node_table_id(@dataset_version)%>"
       id="<%= dom_id(node)%>_child_node_table" 
       data-url="<%= sort_dataset_version_nodes_path(@dataset_version) %>">
  <thead>
    <tr>
      <th width="10">Type</th>
      <th width="">
        Name
        <div class="text-muted">Annotation/Data Dictionary Name</div>
      </th>
      <th width=""></th>
      <th width="">Governance</th>
      <th></th>
    </tr>
  </thead>
  <% sorted_child_nodes = node.child_nodes.sorted %>
  <% sorted_child_nodes.each do |child_node| %>
    <tbody id="body_<%= dom_id(child_node) %>"> 
      <%= render 'dataset_versions/details', node: child_node %>
      <% if divider && child_node != sorted_child_nodes.last %>
        <tr class="divider">
          <td colspan="5" class="text-center"><b><%= divider %></b></td>
        </tr>
      <% end %>
      <%= render 'nodes/era_fields', node: child_node %>
    </tbody>
  <% end %>
</table>

app/views/dataset_versions/_details.html.erb
<tr class="<%= node.highlighting %>" id="<%= dom_id(node) %>">
  <td><%= node_type_label(node) %></td>
  <td>
    <%= content_tag(:div, content_tag(:label, node.reference, class: 'label label-info')) %>
    <%= node.data_item? ? node.name : link_to(node.name, node: node.id) %>
    <%= content_tag(:div, node.annotation, class: 'text-muted') unless node.annotation == 'TEMP ANNOTATION' || node.name == node.annotation %>
  </td>
  <% if node.dataset.dataset_type_name == 'table_specification' || node.group? %>
    <td></td>
  <% else %>
    <td><%= node.min_occurs %>..<%= node.max_occurrences_star %></td>
  <% end %>
  <td><%= node.governance&.value %></td>
  <td rowspan="2">
    <div class="pull-right">
      <% if can?(:destroy, node) %>
        <%= delete_link(node_path(node), method: :delete, remote: true, data: { confirm: "Are you sure you want to remove #{node.name} from #{@dataset_version.name}?" }, skip_authorization: true)%>
      <% end %>
      <% if can?(:update, node) %>
        <%= edit_link edit_node(node), remote: true, skip_authorization: true %>
      <% end %>
      <% if can?(:read, node) && node.data_item? %>
        <%= details_link detail_node(node), remote: true, skip_authorization: true %>
      <% end %>
    </div>
  </td>
</tr>
<tr></tr>
<tr id="<%= dom_id(node) %>_description" class="<%= node.highlighting %>">
  <td style="border-top: 0;padding-top: 0;" colspan="4"><small><%= node.description %></small></td>
</tr>

app/views/dataset_versions/_form.html.erb
<%= bootstrap_form_for([@dataset, @dataset_version], horizontal: true) do |form| %>
  <%= form.control_group :semver_version, 'Semantic Version' do %>
    <%= form.text_field :semver_version %>
  <% end %>
  <%= button_control_group nil do %>
    <div class='pull-right'>
      <%= close_modal %>
      <%= submit_tag('Save', class: 'btn btn-primary', disable_with: 'Saving&hellip;'.html_safe) %>
    <div/>
  <% end %>
<% end %>

app/views/dataset_versions/_invalid_nodes.html.erb
<div id="node-errors">
  <% if @dataset_version_invalid_nodes.present? %>
    <table class="table table-hover" id="node_errors_table">
      <thead>
        <tr>
          <th width="10">Type</th>
          <th width="20%">Name</th>
          <th width="30%">Errors</th>
          <th width="30%">Warnings</th>
          <th width="10%"></th>
        </tr>
      </thead>
      <tbody>      
        <% @dataset_version_invalid_nodes.each do |node| %>
          <%= render 'nodes/error_details', node: node %>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/dataset_versions/_nodes.html.erb
<div id="data-items-panel">
  <table class="table table-hover" id="data_source_items_table">
    <thead>
      <tr>
        <th width="10">Type</th>
        <th width="15%">Name</th>
        <th width="15%">Annotation/Data Dictionary Name</th>
        <th width="30%">Description</th>
        <th width="3%">Min Occurs</th>
        <th width="3%">Max Occurs</th>
        <th width="10%">Governance</th>
        <th width="4%">Child nodes</th>
        <th width="10%"></th>
      </tr>
    </thead>
    <tbody>
      <% node = @dataset_version.version_entity %>
      <%= render 'nodes/details', node: node %>
      <%= render 'nodes/child_node_details', node: node %>
    </tbody>
  </table>
</div>

app/views/dataset_versions/_publish.html.erb
<% if can?(:publish, DatasetVersion) %>
  <%= form_with(url: publish_dataset_version_path(@dataset_version, state: 1), action: :publish, method: :patch, local: false, html: { style: 'display: inline;' }) do |form| %>  
    <%= button_tag('Publish', type: 'submit', class: 'btn-sm btn-primary') %>
  <% end %>
<% end %>

app/views/dataset_versions/_user_actions.html.erb
<div class="row" id="dataset-version-publish" style="margin-bottom: 20px">
  <div class="col-md-12 text-left">
    <%= dataset_download_link %>
    <%= publish_link %>    
  </div>
</div>

app/views/dataset_versions/_version.html.erb
<tr class="<%= publish_tr_class(version) %>">
  <td><%= version.dataset.team&.name %></td>
  <td>
    <% if first %>
      <% if dataset_versions_for_user(version.dataset).count > 1 && first %>
        <% target = "#{dom_id(version.dataset)}_historical_versions" %>
        <%#= link_to() %>
        <a role="button" data-toggle="collapse" data-target="#<%= target %>" aria-expanded="false" aria-controls="<%= target %>">
          <%= version.dataset.name %>
        </a>
      <% else %>
        <%= version.dataset.name %>
      <% end %>
    <% end %>
  </td>
  <td><%= version.semver_version %></td>
  <td colspan="2"><%= version.dataset.full_name %></td>
  <td class="text-right"><%= version.data_items.length %></td>
  <td><%= version.dataset.terms.nil? ? 'None' : 'Y' %></td>
  <!-- TODO: Dry up button choices -->
  <td><%= render('datasets/add_new_version', dataset: version.dataset, readonly: readonly) if first %></td>
  <td nowrap="nowrap">
    <div class="pull-right">
      <%= button_group do %>
        <% unless readonly %>
          <% if can?(:destroy, version) %>
            <%= delete_link(version, method: :delete, data: { confirm: "Are you sure you want to delete Dataset: #{version.semver_version}" } )%>
          <% end %>
          <% if can?(:update, version) %>
             <%= edit_link version, remote: true %>
          <% end %>
        <% end%>
        <%= details_link version %>
      <% end %>      
    </div>
  </td>
</tr>

app/views/dataset_versions/create.js.erb
<%
  @datasets ||= Dataset.all
  @datasets = @datasets.paginate(page: params[:page], per_page: 15)
  dataset ||= @dataset_version.dataset
%>

jQuery('#modal').modal('hide');
window.location.reload();
// jQuery('#datasets').replaceWith(
//   '<%= escape_javascript(render 'datasets/datasets_table') %>');
// jQuery('#<%= dom_id(dataset) %>_versions').collapse('show')

app/views/dataset_versions/destroy.js.erb
window.location.reload();

app/views/dataset_versions/edit.html.erb
<h1>Editing <%= @dataset_version.name %></h1>

<%= bootstrap_form_for @dataset_version, horizontal: 2 do |form| %>
  <%= render 'form', { form: form} %>
<% end %>

app/views/dataset_versions/edit.js.erb
<%
  html_content = escape_javascript bootstrap_form_for(@dataset_version, remote: true, horizontal: 2) { |form| render('form', form: form) }
%>

jQuery('#modal_title').html("Editing Dataset Version: <%= @dataset_version.semver_version %>");
jQuery('#modal_body').html('<%= html_content %>').parents('.modal').modal('show');

app/views/dataset_versions/index.js.erb
<%
  @datasets = Dataset.all
  dataset ||= @dataset_version.dataset
%>

jQuery('#modal').modal('hide');
jQuery('#datasets_information').replaceWith(
  '<%= escape_javascript(render 'datasets/datasets_table') %>');
jQuery('#<%= dom_id(dataset) %>_versions').collapse('show')

app/views/dataset_versions/new.js.erb
<%
  html_content = escape_javascript bootstrap_form_for([@dataset, @dataset_version], remote: true, horizontal: true) { |form| render('form', form: form) }
%>

jQuery('#modal_title').html('Add a new Dataset Version');
jQuery('#modal_body').html('<%= html_content %>').parents('.modal').modal('show');