config/routes.rb
Rails.application.routes.draw do
  mount NdrError::Engine => '/fingerprinting'
  mount NdrAuthenticate::Engine, at: '/auth' if Rails.configuration.x.use_ndr_authenticate

  get '/users/sign_in', to: redirect('/auth/sign_in') if Rails.configuration.x.use_ndr_authenticate

  # NOTE: NdrAuth cannot at present pick up a custom `after_sign_in_path_for` defined by the
  # host app. Since it will always redirect to `main_app.root_path` we can instead change what
  # controller/action the host app understands '/' to be for different contexts and achieve a
  # similar result.
  authenticated :user, ->(user) { !user.standard? } do
    root 'projects#dashboard', as: :non_standard_authenticated_root
  end

  authenticated :user, ->(user) { user.cas_role? } do
    root 'projects#index', as: :cas_role_authenticated_root
  end

  authenticated :user, ->(user) { user.standard? && !user.cas_role? } do
    root 'home#index', as: :applicant_authenticated_root
  end

  root 'home#index'

  concern :downloadable do
    get :download, on: :member
  end

  concern :commentable do |options|
    defaults = {
      shallow: true,
      only:    %i[index create destroy]
    }

    resources :comments, defaults.merge(options)
  end

  concern :approvable do |options|
    default_options = {
      only: %i[new create destroy]
    }

    resource :approval,  default_options.merge(options)
    resource :rejection, default_options.merge(options)
  end

  get 'notifications/index'
  get '/reports/report1', to: 'reports#report1', as: 'report1'
  get '/reports/report2', to: 'reports#report2', as: 'report2'

  resources :reports, only: %i[show]

  get '/downloads/data_access_agreement', to: 'downloads#data_access_agreement',
                                          as: 'data_access_agreement'
  get '/downloads/ons_declaration_of_use', to: 'downloads#ons_declaration_of_use',
                                           as: 'ons_declaration_of_use'
  get '/downloads/ons_short_declaration_list', to: 'downloads#ons_short_declaration_list',
                                               as: 'ons_short_declaration_list'
  get '/downloads/terms_and_conditions_doc', to: 'downloads#terms_and_conditions_doc',
                                         as: 'terms_and_conditions_doc'
  get '/downloads/project_end_users_template_csv', to: 'downloads#project_end_users_template_csv',
      as: 'project_end_users_template_csv'

  # for dynamic select boxes in team and user
  get 'filter_delegates_by_division', to: 'users#filter_delegates_by_division',
                                      as: 'filter_delegates_by_division'

  get 'ons_template', to: 'projects#ons_template'

  # TODO: Remove once NdrAuthenticate is ready for the prime time.
  unless Rails.configuration.x.use_ndr_authenticate
    devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' },
                       skip: :saml_authenticatable
  end

  resources :notifications, :directorates, :divisions

  resources :users do
    resources :grants, only: [:index] do
      collection do
        get :edit_team
        get :edit_system
        get :edit_project
        get :edit_dataset
        patch :update
      end
    end
    get :teams
    get :projects
  end

  resources :projects do
    get :dashboard, on: :collection
    get :cas_approvals, on: :collection
    patch :project_dataset_levels_bulk_approvals, on: :member
    put :project_dataset_levels_bulk_approvals, on: :member
    patch :project_dataset_levels_bulk_renewal_requests, on: :member
    put :project_dataset_levels_bulk_renewal_requests, on: :member
  end

  resources :projects, shallow: true do
    resources :project_datasets, shallow: true do
      resources :project_dataset_levels do
        member do
          patch :approve
          put :approve
          patch :reject
          put :reject
          patch :reapply
          put :reapply
          patch :renew
          get :renew
        end
      end
    end
  end

  get :servicestatus, to: 'home#servicestatus'
  resources :home, only: [:index]

  resources :terms_and_conditions, only: [:index, :create]

  resources :active_team, only: [:index, :update]

  resources :data_sources, shallow: true do
    resources :data_source_items
  end

  resources :table_specifications, only: [:index]
  resources :data_assets, only: [:index]
  resources :datasets, shallow: true do
    resources :dataset_versions, shallow: true do
      resources :categories
      resources :nodes do
        collection do
          patch :sort
        end
        resources :node_categories do
          collection do
            patch :update
          end
        end
      end
      resources :data_items do
        member do
          get :edit_error, to: 'data_items#edit_error', as: :edit_error
          patch :edit_error, to: 'data_items#update_error', as: :update_error
        end
      end
      resources :entities do
        member do
          get :edit_error, to: 'entities#edit_error', as: :edit_error
          patch :edit_error, to: 'entities#update_error', as: :update_error
        end
      end
      resources :choices do
        member do
          get :edit_error, to: 'choices#edit_error', as: :edit_error
          patch :edit_error, to: 'choices#update_error', as: :update_error
        end
      end
      resources :groups do
        member do
          get :edit_error, to: 'groups#edit_error', as: :edit_error
          patch :edit_error, to: 'groups#update_error', as: :update_error
        end
      end
      resources :category_choices, :node_errors
      patch :publish, on: :member
      get "download/:id" => "dataset_versions#download", as: :download
    end
  end

  resources :user_notifications
  patch :mark_notification_as_read, to: 'user_notifications#mark_as_read'

  resources :organisations, shallow: true do
    resources :teams
  end

  patch :default_address, to: 'addresses#default_address'

  resources :teams, shallow: true, except: %i[new create] do
    resources :datasets
    resources :memberships
    resources :grants, controller: :team_grants do
      collection do
        get :edit
        patch :update
      end
    end
    resources :team_datasets, only: [:index, :new, :create, :destroy]
    resources :projects, shallow: true, concerns: %i[commentable] do
      resources :grants, controller: :project_grants do
        collection do
          get :edit
          patch :update
        end
      end
      resources :project_memberships, only: [:index, :new, :create, :destroy]
      resources :project_data_end_users
      resources :project_attachments

      resources :project_nodes, except: %i[edit update], concerns: %i[commentable] do
        concerns :approvable, module: 'project_nodes'

        collection do
          scope :bulk, module: :project_nodes, only: %i[new create destroy] do
            resource :approvals,  controller: :bulk_approvals,  as: :project_nodes_bulk_approval
            resource :rejections, controller: :bulk_rejections, as: :project_nodes_bulk_rejection
          end
        end
      end

      resources :amendments, controller: :project_amendments, as: :project_amendments
      resources :data_privacy_impact_assessments, concerns: %i[downloadable]
      resources :contracts, concerns: %i[downloadable]
      resources :releases
      resources :communications, except: %i[show edit update], concerns: %i[commentable]

      namespace :workflow do
        resources :project_states, only: [] do
          concerns :commentable, controller: '/comments'
          resources :assignments, only: %i[create]
        end
      end

      collection do
        post :import, controller: 'projects/imports', action: :create
      end

      resources :imports, only: :create, controller: 'projects/imports'

      resource :details, only: [], concerns: %i[approvable], module: 'projects/details'
      resource :legal,   only: [], concerns: %i[approvable], module: 'projects/legal'
      resource :members, only: [], concerns: %i[approvable], module: 'projects/members'

      member do
        # FIXME: This should be PATCH
        get :reset_project_approvals
        get :edit_data_source_items
        get :edit_ons_data_access
        get :edit_ons_declaration
        get :show_ons_access_agreement
        get :show_ons_declaration_use
        get :show_ons_declaration_list
        get :duplicate
        patch :assign
        patch :transition
      end
    end
  end

  resources :jobs, only: %i[index show destroy]

  get '/terms_rejected', to: 'terms_and_conditions#terms_rejected', as: 'terms_rejected'

  get ':resource_type/:resource_id/versions',     to: 'versions#index', as: :papertrail_versions
  get ':resource_type/:resource_id/versions/:id', to: 'versions#show',  as: :papertrail_version

  # Allowing logged-in user to change their password:
  get  'change_password', to: 'users/password_changes#new'
  post 'change_password', to: 'users/password_changes#create'
end

app/models/category.rb
# COSD Categories e.g Breast, CNS, Other
class Category < ApplicationRecord
  has_many :node_categories, foreign_key: 'category_id', inverse_of: :category,
                             dependent: :destroy
  has_many :nodes, through: :node_categories, foreign_key: 'node_id'

  belongs_to :dataset_version

  validates :name, uniqueness: { scope: :dataset_version,
                                 message: 'One occurrence per version' }

  before_destroy prepend: true do
    throw(:abort) if in_use?
  end
  
  def in_use?
    NodeCategory.where(category_id: id).count.positive?
  end
end

app/controllers/categories_controller.rb
# Controller for Category Choice Nodes
class CategoriesController < NodesController
  load_and_authorize_resource :dataset_version
  load_and_authorize_resource class: 'Category', through: :dataset_version, shallow: true

  respond_to :js, :html

  def new; end

  def show; end

  def create
    if @category.save
      @categories = @category.dataset_version.categories
      respond_to do |format|
        msg = 'Category was successfully created.'
        format.html { redirect_to dataset_version_categories_path, notice: msg }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @dataset_version = @category.dataset_version
  end

  def update
    if @category.update(category_params)
      @categories = @category.dataset_version.categories
      @dataset_version = @category.dataset_version
      respond_to do |format|
        msg = 'Category successfully updated.'
        format.html { redirect_to dataset_version_categories_path(@dataset_version), notice: msg }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @categories = @category.dataset_version.categories
    @dataset_version = @category.dataset_version
    if @category.destroy
      respond_to do |format|
        msg = 'Category was successfully destroyed.'
        format.html { redirect_to dataset_version_categories_path(@dataset_version), notice: msg}
        format.js
      end
    else
      respond_to do |format|
        msg = 'Could not destroy category!'
        format.html { redirect_to dataset_version_categories_path(@dataset_version), notice: msg }
        format.js { render js: "alert('#{msg}')" }
      end
    end
  end

  def category_params
    params.require(:category).permit(
      :id, :name, :dataset_version_id, :sort
    )
  end
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for([@dataset_version, @category],
    url: dataset_version_categories_path(@dataset_version, @category),
    horizontal: true) do |form| %>
  <%= form.hidden_field :dataset_version_id, value: @dataset_version.id %>
  <%= form.hidden_field :sort, value: 0 %>
  <%= form.control_group(:name) { form.text_field :name } %>
  <%= form.control_group(:description) { form.text_field :description } %>
  <%= button_control_group nil do %>
    <div class='pull-right'>
      <%= close_modal %>
      <%= submit_tag('Save', class: 'btn btn-primary', disable_with: 'Saving&hellip;'.html_safe) %>
    <div/>
  <% end %>
<% end %>

app/views/categories/_table.html.erb
<div id='dataset-version-categories'>
  <%= link_to('Back to Dataset Version', @dataset_version, class: 'btn btn-default')%>
  <table class="table table-hover" id="dataset-version-category-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
      </tr>
      <div class="pull-right">
        <% if can?(:update, Category) %>
          <%= link_to bootstrap_icon_tag('plus') +' Add New Category', new_dataset_version_category_path(@dataset_version), remote: true, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr id="<%= dom_id(category) %>">
          <td><%= category.name %></td>
          <td><%= category.description %></td>
          <td>
            <div class="pull-right">
              <%= button_group do %>
                <% if can?(:destroy, category) %>
                  <%= delete_link(category, method: :delete, remote: true, data:
                      { confirm: "Are you sure you want to delete Category: #{category.name}" } )
                  %>
                <% end %>
                <% if can?(:update, category) %>
                   <%= edit_link edit_category_path(category), remote: true, skip_authorization: true %>
                <% end %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/create.js.erb
jQuery('#modal').modal('hide');
jQuery('#dataset-version-categories').replaceWith(
  '<%= escape_javascript(render 'categories/table') %>');

app/views/categories/destroy.js.erb
jQuery('#<%= dom_id(@category) %>').hide('fast');

app/views/categories/edit.html.erb
<h1>Editing <%= @category.name %></h1>

<%= bootstrap_form_for @category, url: category_path(@category), horizontal: 2 do |form| %>
  <%= render 'form', { form: form } %>
<% end %>

app/views/categories/edit.js.erb
  <%
    html_content = escape_javascript bootstrap_form_for(
      @category, url: category_path(@category),
      remote: true, horizontal: 2) { |form| render('form', form: form) }
  %>

jQuery('#modal_title').html("Editing Category: <%= @category.name %>");
jQuery('#modal_body').html('<%= html_content %>').parents('.modal').modal('show');

app/views/categories/index.html.erb
<%= render 'table' %>

app/views/categories/new.html.erb
<h1>Create a new <%= @category.name %> </h1>
<%= render 'form' %>

app/views/categories/new.js.erb
<%
  html_content = escape_javascript bootstrap_form_for(
    [@dataset_version, @category], remote: true, horizontal: true) { |form| render('form', form: form) }
%>

jQuery('#modal_title').html('Add a new Category');
jQuery('#modal_body').html('<%= html_content %>').parents('.modal').modal('show');

app/views/categories/show.html.erb
<%= render 'publish' %>
<%= render 'nodes' %>

app/views/categories/update.js.erb
jQuery('#modal').modal('hide');
jQuery('#dataset-version-categories').replaceWith(
  '<%= escape_javascript(render 'categories/table') %>');